apiVersion: apps/v1
kind: Deployment
metadata:
  name: desafio-sre
spec:
  replicas: 1
  selector:
    matchLabels:
      app: desafio-sre
  template:
    metadata:
      labels:
        app: desafio-sre
    spec:
      containers:
      - name: desafio-sre
        image: gersontpc/desafio-sre-app:v1.0.0-x64
        ports:
        - containerPort: 8080
        env:
        - name: OTEL_SDK_DISABLED
          value: "true"
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "http://localhost:4318/v1/metrics"
        - name: OTEL_SERVICE_NAME
          value: "app-name"
        - name: OTEL_INSTRUMENTATION_LIBRARY_NAMES
          value: "java.util.logging"
        resources:
          limits:
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 220
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 260
          periodSeconds: 10
