apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: desafio-sre-ingress
spec:
  rules:
  - http:
      paths:
      - path: /actuator
        pathType: Prefix
        backend:
          service:
            name: desafio-sre-service
            port:
              number: 8080
      - path: /actuator/prometheus
        pathType: Prefix
        backend:
          service:
            name: my-kube-prometheus-stack-prometheus
            port:
              number: 9090
      - path: /actuator/metrics
        pathType: Prefix
        backend:
          service:
            name: my-kube-prometheus-stack-kube-state-metrics
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-kube-prometheus-stack-grafana
            port:
              number: 80
